// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  AuthenticateUserData,
  AuthenticateUserErrors,
  AuthenticateUserResponses,
  CreateContactData,
  CreateContactResponses,
  CsrfData,
  CsrfResponses,
  GetAllContactsData,
  GetAllContactsResponses,
  GetContactByIdData,
  GetContactByIdErrors,
  GetContactByIdResponses,
  HelloWorldData,
  HelloWorldResponses,
  LogoutData,
  LogoutResponses,
  MeData,
  MeResponses,
  PatchContactData,
  PatchContactErrors,
  PatchContactResponses,
  RegisterUserData,
  RegisterUserErrors,
  RegisterUserResponses,
  VerifyUserData,
  VerifyUserErrors,
  VerifyUserResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get all contacts
 *
 * Retrieve a paginated list of contacts with optional filtering
 */
export const getAllContacts = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllContactsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetAllContactsResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "phonebook_auth",
        type: "apiKey",
      },
    ],
    url: "/api/contacts",
    ...options,
  });

/**
 * Create a new contact
 *
 * Create a new contact with the provided details
 */
export const createContact = <ThrowOnError extends boolean = false>(
  options: Options<CreateContactData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateContactResponses,
    unknown,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "phonebook_auth",
        type: "apiKey",
      },
    ],
    url: "/api/contacts",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Verify user and confirm registration
 *
 * Verifies a user account and enables it
 */
export const verifyUser = <ThrowOnError extends boolean = false>(
  options: Options<VerifyUserData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    VerifyUserResponses,
    VerifyUserErrors,
    ThrowOnError
  >({
    url: "/api/auth/verify",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Register a new user
 *
 * Creates a new user account with the provided registration details
 */
export const registerUser = <ThrowOnError extends boolean = false>(
  options: Options<RegisterUserData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    RegisterUserResponses,
    RegisterUserErrors,
    ThrowOnError
  >({
    url: "/api/auth/signup",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Logout
 *
 * Clears the authentication cookie
 */
export const logout = <ThrowOnError extends boolean = false>(
  options?: Options<LogoutData, ThrowOnError>,
) =>
  (options?.client ?? client).post<LogoutResponses, unknown, ThrowOnError>({
    security: [
      {
        in: "cookie",
        name: "phonebook_auth",
        type: "apiKey",
      },
    ],
    url: "/api/auth/logout",
    ...options,
  });

/**
 * Authenticate a user
 *
 * Authenticates a user and sets a secure HttpOnly authentication cookie
 */
export const authenticateUser = <ThrowOnError extends boolean = false>(
  options: Options<AuthenticateUserData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AuthenticateUserResponses,
    AuthenticateUserErrors,
    ThrowOnError
  >({
    url: "/api/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get contact by ID
 *
 * Retrieve a single contact by its ID
 */
export const getContactById = <ThrowOnError extends boolean = false>(
  options: Options<GetContactByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetContactByIdResponses,
    GetContactByIdErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "phonebook_auth",
        type: "apiKey",
      },
    ],
    url: "/api/contacts/{id}",
    ...options,
  });

/**
 * Update a contact
 *
 * Update an existing contact's details
 */
export const patchContact = <ThrowOnError extends boolean = false>(
  options: Options<PatchContactData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    PatchContactResponses,
    PatchContactErrors,
    ThrowOnError
  >({
    security: [
      {
        in: "cookie",
        name: "phonebook_auth",
        type: "apiKey",
      },
    ],
    url: "/api/contacts/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const helloWorld = <ThrowOnError extends boolean = false>(
  options?: Options<HelloWorldData, ThrowOnError>,
) =>
  (options?.client ?? client).get<HelloWorldResponses, unknown, ThrowOnError>({
    security: [
      {
        in: "cookie",
        name: "phonebook_auth",
        type: "apiKey",
      },
    ],
    url: "/api/helloworld",
    ...options,
  });

/**
 * Get authenticated user
 *
 * Returns the currently authenticated user
 */
export const me = <ThrowOnError extends boolean = false>(
  options?: Options<MeData, ThrowOnError>,
) =>
  (options?.client ?? client).get<MeResponses, unknown, ThrowOnError>({
    security: [
      {
        in: "cookie",
        name: "phonebook_auth",
        type: "apiKey",
      },
    ],
    url: "/api/auth/me",
    ...options,
  });

/**
 * Get CSRF token
 *
 * Returns the CSRF token required for state-changing requests
 */
export const csrf = <ThrowOnError extends boolean = false>(
  options?: Options<CsrfData, ThrowOnError>,
) =>
  (options?.client ?? client).get<CsrfResponses, unknown, ThrowOnError>({
    url: "/api/auth/csrf",
    ...options,
  });
