// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  CreateContactData,
  CreateContactResponses,
  GetAllContactsData,
  GetAllContactsResponses,
  GetContactByIdData,
  GetContactByIdErrors,
  GetContactByIdResponses,
  HelloWorldData,
  HelloWorldResponses,
  PatchContactData,
  PatchContactErrors,
  PatchContactResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get all contacts
 *
 * Retrieve a paginated list of contacts with optional filtering
 */
export const getAllContacts = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllContactsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetAllContactsResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/contacts", ...options });

/**
 * Create a new contact
 *
 * Create a new contact with the provided details
 */
export const createContact = <ThrowOnError extends boolean = false>(
  options: Options<CreateContactData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateContactResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/contacts",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get contact by ID
 *
 * Retrieve a single contact by its ID
 */
export const getContactById = <ThrowOnError extends boolean = false>(
  options: Options<GetContactByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetContactByIdResponses,
    GetContactByIdErrors,
    ThrowOnError
  >({ url: "/api/contacts/{id}", ...options });

/**
 * Update a contact
 *
 * Update an existing contact's details
 */
export const patchContact = <ThrowOnError extends boolean = false>(
  options: Options<PatchContactData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    PatchContactResponses,
    PatchContactErrors,
    ThrowOnError
  >({
    url: "/api/contacts/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const helloWorld = <ThrowOnError extends boolean = false>(
  options?: Options<HelloWorldData, ThrowOnError>,
) =>
  (options?.client ?? client).get<HelloWorldResponses, unknown, ThrowOnError>({
    url: "/api/helloworld",
    ...options,
  });
