// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:8080" | (string & {});
};

export type CreateContactRequest = {
  firstName?: string;
  lastName?: string;
  address?: string;
  phoneNumber?: string;
  age?: number;
};

export type ContactDto = {
  id?: number;
  firstName?: string;
  lastName?: string;
  address?: string;
  phoneNumber?: string;
  age?: number;
  deleted?: boolean;
};

export type PatchContactRequest = {
  firstName?: string;
  lastName?: string;
  address?: string;
  phoneNumber?: string;
  age?: number;
  deleted?: boolean;
};

export type PageMetadata = {
  size?: number;
  number?: number;
  totalElements?: number;
  totalPages?: number;
};

export type PagedModelContactDto = {
  content?: Array<ContactDto>;
  page?: PageMetadata;
};

export type GetAllContactsData = {
  body?: never;
  path?: never;
  query?: {
    filter?: string;
    deleted?: boolean;
    /**
     * Zero-based page index (0..N)
     */
    page?: number;
    /**
     * The size of the page to be returned
     */
    size?: number;
    /**
     * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    sort?: Array<string>;
  };
  url: "/api/contacts";
};

export type GetAllContactsResponses = {
  /**
   * OK
   */
  200: PagedModelContactDto;
};

export type GetAllContactsResponse =
  GetAllContactsResponses[keyof GetAllContactsResponses];

export type CreateContactData = {
  body: CreateContactRequest;
  path?: never;
  query?: never;
  url: "/api/contacts";
};

export type CreateContactResponses = {
  /**
   * Contact created successfully
   */
  201: ContactDto;
};

export type CreateContactResponse =
  CreateContactResponses[keyof CreateContactResponses];

export type GetContactByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/contacts/{id}";
};

export type GetContactByIdErrors = {
  /**
   * Contact not found
   */
  404: ContactDto;
};

export type GetContactByIdError =
  GetContactByIdErrors[keyof GetContactByIdErrors];

export type GetContactByIdResponses = {
  /**
   * Contact found
   */
  200: ContactDto;
};

export type GetContactByIdResponse =
  GetContactByIdResponses[keyof GetContactByIdResponses];

export type PatchContactData = {
  body: PatchContactRequest;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/contacts/{id}";
};

export type PatchContactErrors = {
  /**
   * Contact not found
   */
  404: ContactDto;
};

export type PatchContactError = PatchContactErrors[keyof PatchContactErrors];

export type PatchContactResponses = {
  /**
   * Contact updated successfully
   */
  200: ContactDto;
};

export type PatchContactResponse =
  PatchContactResponses[keyof PatchContactResponses];

export type HelloWorldData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/helloworld";
};

export type HelloWorldResponses = {
  /**
   * OK
   */
  200: string;
};

export type HelloWorldResponse = HelloWorldResponses[keyof HelloWorldResponses];
