// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:8080" | (string & {});
};

export type CreateContactRequest = {
  firstName?: string;
  lastName?: string;
  address?: string;
  phoneNumber?: string;
  age?: number;
};

export type ContactResponse = {
  id?: number;
  firstName?: string;
  lastName?: string;
  address?: string;
  phoneNumber?: string;
  age?: number;
  deleted?: boolean;
};

export type RegisterUserRequest = {
  email: string;
  password: string;
};

export type UserResponse = {
  id?: number;
  email?: string;
};

export type AuthenticateUserRequest = {
  email: string;
  password: string;
};

export type LoginResponse = {
  expiresIn?: number;
};

export type PatchContactRequest = {
  firstName?: string;
  lastName?: string;
  address?: string;
  phoneNumber?: string;
  age?: number;
  deleted?: boolean;
};

export type PageMetadata = {
  size?: number;
  number?: number;
  totalElements?: number;
  totalPages?: number;
};

export type PagedModelContactResponse = {
  content?: Array<ContactResponse>;
  page?: PageMetadata;
};

export type GetAllContactsData = {
  body?: never;
  path?: never;
  query?: {
    filter?: string;
    deleted?: boolean;
    /**
     * Zero-based page index (0..N)
     */
    page?: number;
    /**
     * The size of the page to be returned
     */
    size?: number;
    /**
     * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     */
    sort?: Array<string>;
  };
  url: "/api/contacts";
};

export type GetAllContactsResponses = {
  /**
   * OK
   */
  200: PagedModelContactResponse;
};

export type GetAllContactsResponse =
  GetAllContactsResponses[keyof GetAllContactsResponses];

export type CreateContactData = {
  body: CreateContactRequest;
  path?: never;
  query?: never;
  url: "/api/contacts";
};

export type CreateContactResponses = {
  /**
   * Contact created successfully
   */
  201: ContactResponse;
};

export type CreateContactResponse =
  CreateContactResponses[keyof CreateContactResponses];

export type RegisterUserData = {
  body: RegisterUserRequest;
  path?: never;
  query?: never;
  url: "/api/auth/signup";
};

export type RegisterUserErrors = {
  /**
   * Invalid input or email already registered
   */
  400: string;
};

export type RegisterUserError = RegisterUserErrors[keyof RegisterUserErrors];

export type RegisterUserResponses = {
  /**
   * User successfully registered
   */
  200: UserResponse;
};

export type RegisterUserResponse =
  RegisterUserResponses[keyof RegisterUserResponses];

export type LogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/auth/logout";
};

export type LogoutResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type AuthenticateUserData = {
  body: AuthenticateUserRequest;
  path?: never;
  query?: never;
  url: "/api/auth/login";
};

export type AuthenticateUserErrors = {
  /**
   * Invalid input or user not registered
   */
  400: string;
  /**
   * Invalid credentials
   */
  401: string;
};

export type AuthenticateUserError =
  AuthenticateUserErrors[keyof AuthenticateUserErrors];

export type AuthenticateUserResponses = {
  /**
   * Successfully authenticated
   */
  200: LoginResponse;
};

export type AuthenticateUserResponse =
  AuthenticateUserResponses[keyof AuthenticateUserResponses];

export type GetContactByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/contacts/{id}";
};

export type GetContactByIdErrors = {
  /**
   * Contact not found
   */
  404: unknown;
};

export type GetContactByIdResponses = {
  /**
   * Contact found
   */
  200: ContactResponse;
};

export type GetContactByIdResponse =
  GetContactByIdResponses[keyof GetContactByIdResponses];

export type PatchContactData = {
  body: PatchContactRequest;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/contacts/{id}";
};

export type PatchContactErrors = {
  /**
   * Contact not found
   */
  404: unknown;
};

export type PatchContactResponses = {
  /**
   * Contact updated successfully
   */
  200: ContactResponse;
};

export type PatchContactResponse =
  PatchContactResponses[keyof PatchContactResponses];

export type HelloWorldData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/helloworld";
};

export type HelloWorldResponses = {
  /**
   * OK
   */
  200: string;
};

export type HelloWorldResponse = HelloWorldResponses[keyof HelloWorldResponses];

export type MeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/auth/me";
};

export type MeResponses = {
  /**
   * OK
   */
  200: UserResponse;
};

export type MeResponse = MeResponses[keyof MeResponses];

export type CsrfData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/auth/csrf";
};

export type CsrfResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: string;
  };
};

export type CsrfResponse = CsrfResponses[keyof CsrfResponses];
