// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:8080" | (string & {});
};

export type CreateContactRequest = {
  firstName?: string;
  lastName?: string;
  address?: string;
  phoneNumber?: string;
  age?: number;
};

export type ContactDto = {
  id?: number;
  firstName?: string;
  lastName?: string;
  address?: string;
  phoneNumber?: string;
  age?: number;
  deleted?: boolean;
};

export type PatchContactRequest = {
  firstName?: string;
  lastName?: string;
  address?: string;
  phoneNumber?: string;
  age?: number;
  deleted?: boolean;
};

export type Pageable = {
  page?: number;
  size?: number;
  sort?: Array<string>;
};

export type PageContactDto = {
  totalElements?: number;
  totalPages?: number;
  pageable?: PageableObject;
  size?: number;
  content?: Array<ContactDto>;
  number?: number;
  sort?: SortObject;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  empty?: boolean;
};

export type PageableObject = {
  paged?: boolean;
  pageNumber?: number;
  pageSize?: number;
  offset?: number;
  sort?: SortObject;
  unpaged?: boolean;
};

export type SortObject = {
  sorted?: boolean;
  empty?: boolean;
  unsorted?: boolean;
};

export type GetAllContactsData = {
  body?: never;
  path?: never;
  query: {
    filter?: string;
    pageable: Pageable;
  };
  url: "/api/contacts";
};

export type GetAllContactsResponses = {
  /**
   * OK
   */
  200: PageContactDto;
};

export type GetAllContactsResponse =
  GetAllContactsResponses[keyof GetAllContactsResponses];

export type CreateContactData = {
  body: CreateContactRequest;
  path?: never;
  query?: never;
  url: "/api/contacts";
};

export type CreateContactResponses = {
  /**
   * Contact created successfully
   */
  201: ContactDto;
};

export type CreateContactResponse =
  CreateContactResponses[keyof CreateContactResponses];

export type GetContactByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/contacts/{id}";
};

export type GetContactByIdErrors = {
  /**
   * Contact not found
   */
  404: ContactDto;
};

export type GetContactByIdError =
  GetContactByIdErrors[keyof GetContactByIdErrors];

export type GetContactByIdResponses = {
  /**
   * Contact found
   */
  200: ContactDto;
};

export type GetContactByIdResponse =
  GetContactByIdResponses[keyof GetContactByIdResponses];

export type PatchContactData = {
  body: PatchContactRequest;
  path: {
    id: number;
  };
  query?: never;
  url: "/api/contacts/{id}";
};

export type PatchContactErrors = {
  /**
   * Contact not found
   */
  404: ContactDto;
};

export type PatchContactError = PatchContactErrors[keyof PatchContactErrors];

export type PatchContactResponses = {
  /**
   * Contact updated successfully
   */
  200: ContactDto;
};

export type PatchContactResponse =
  PatchContactResponses[keyof PatchContactResponses];

export type HelloWorldData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/helloworld";
};

export type HelloWorldResponses = {
  /**
   * OK
   */
  200: string;
};

export type HelloWorldResponse = HelloWorldResponses[keyof HelloWorldResponses];
